Auth_func
honda9135/find_react pull request #2
Opened 2020-10-31 05:53 UTC by honda9135

2020-10-31 08:44 UTC, soimyy requested changes
よくわかりませんが、よいと思います

2020-10-31 08:44 UTC, soimyy requested changes
マスターへマージします

2020-10-31 08:49 UTC, soimyy commented
コンフリクトが起こっているから、解決してください。

先に、
ボトムナビゲーションのブランチをマスターにマージしたから
そこの変更の差分で、コンフリクトが起こっています。

2020-11-02 00:23 UTC, honda9135 commented
了解した！今日中にはする

2020-11-02 01:17 UTC, merged